language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5
  - 1.6
  - tip

env:
  - CGO_CFLAGS="-I./leveldb-master/include"
  - CGO_LDFLAGS="-L./leveldb-master./out-shared -lsnappy"

before_install:
  - sudo apt-get install -y libsnappy-dev
  - ./install-levigo.sh

