language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5
  - 1.6
  - tip

before_install:
  - sudo apt-get install -y libsnappy-dev
  - ./install-leveldb.sh

before_script:
  - CGO_CFLAGS="-I./leveldb-master/include" CGO_LDFLAGS="-L./leveldb-master/out-shared -lsnappy" go get github.com/jmhodges/levigo
